version: '3.8'

services:
  onlyoffice:
    image: onlyoffice/documentserver:8.2.2
    container_name: OnlyOfficeDocumentServer
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=OnlyOfficeDocumentServer
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgres
      - DB_PORT=5432
      - DB_NAME=${ONLYOFFICE_DB_NAME}
      - DB_USER=${ONLYOFFICE_DB_USER}
      - DB_PWD=${ONLYOFFICE_DB_PASSWORD}
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    volumes:
      - ${APPDATA_PATH}/onlyoffice/logs:/var/log/onlyoffice
      - ${APPDATA_PATH}/onlyoffice/data:/var/www/onlyoffice/Data
      - ${APPDATA_PATH}/onlyoffice/lib:/var/lib/onlyoffice
    labels:
      - "kuma.onlyoffice.name=OnlyOffice Document Server"
      - "kuma.onlyoffice.url=http://onlyoffice:80"
      - "kuma.onlyoffice.method=GET"
      - "kuma.onlyoffice.interval=60"
      - "kuma.onlyoffice.keyword=OnlyOffice"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/onlyoffice-icon.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:8082]"
    ports:
      - "8082:80"
      - "4430:443"
    networks:
      - internal_net
      - db_net
    depends_on:
      - onlyoffice-postgres

  onlyoffice-postgres:
    image: postgres:17.2
    container_name: onlyoffice-postgres
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=onlyoffice-postgres
      - POSTGRES_DB=${ONLYOFFICE_DB_NAME}
      - POSTGRES_USER=${ONLYOFFICE_DB_USER}
      - POSTGRES_PASSWORD=${ONLYOFFICE_DB_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/onlyoffice/postgres:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    labels:
      - "kuma.onlyofficedb.name=OnlyOffice Database"
      - "kuma.onlyofficedb.tcp.host=onlyoffice-postgres"
      - "kuma.onlyofficedb.tcp.port=5432"
      - "kuma.onlyofficedb.interval=120"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/postgresql-icon.png"
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ONLYOFFICE_DB_USER} -d ${ONLYOFFICE_DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  internal_net:
    external: true
  db_net:
    external: true