# services/utilities/dashy/docker-compose.yml
# Optimized for production use
version: '3.8'

services:
  dashy:
    image: lissy93/dashy:release-3.1.1
    container_name: dashy
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - UID=99
      - GID=100
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=dashy
      
      # 🔧 PRODUCTION OPTIMIZATIONS
      - NODE_ENV=production        # Force production mode
      - DISABLE_DEV_MODE=true      # Disable development features
      - PORT=8080
      - DIRECTORY=/app
      - IS_DOCKER=true
      
      # 📊 PERFORMANCE SETTINGS
      - VUE_APP_DOMAIN=/           # Base path optimization
      - BASE_URL=/                 # Static asset path
      
    labels:
      - "kuma.dashy.type=http"
      - "kuma.dashy.url=http://dashy:8080"
      - "kuma.dashy.name=Dashy Dashboard"
      - "kuma.dashy.interval=60"
      - "kuma.dashy.keyword=Dashy"
      - "kuma.dashy.tags=utilities,dashboard"
      # Keep existing Unraid labels
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/dashy-icon.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:4000]"
    volumes:
      - ${APPDATA_PATH}/dashy:/app/user-data
      - ${APPDATA_PATH}/dashy/icons:/app/user-data/item-icons
    ports:
      - "4000:8080"
    networks:
      - internal_net
    
    # 🎯 RESOURCE LIMITS (should drop dramatically)
    deploy:
      resources:
        limits:
          cpus: '0.2'      # Should be very light in production
          memory: 128M     # Down from 225MB!
        reservations:
          cpus: '0.02'
          memory: 32M

networks:
  internal_net:
    external: true