# ============================================================================
# services/productivity/wikijs/docker-compose.yml
# ============================================================================
version: '3.8'

services:
  wikijs:
    image: requarks/wiki:2.5.304
    container_name: wikijs
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=wikijs
      - DB_TYPE=postgres
      - DB_HOST=wikijs-postgres
      - DB_PORT=5432
      - DB_USER=${WIKIJS_DB_USER}
      - DB_PASS=${WIKIJS_DB_PASSWORD}
      - DB_NAME=${WIKIJS_DB_NAME}
    volumes:
      - ${APPDATA_PATH}/wikijs:/wiki/data
    labels:
      - "kuma.monitoring.group.name=Productivity"
      - "kuma.uptime_kuma.name=Wiki.js"
      - "kuma.uptime_kuma.url=http://wikijs:3000"
      - "kuma.uptime_kuma.method=GET"
      - "kuma.uptime_kuma.interval=60"
      - "kuma.uptime_kuma.keyword=Wiki.js"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/wikijs-icon.png"
      - "net.unraid.docker.webui=http://[IP]:[PORT:3000]"
    ports:
      - "3000:3000"
    networks:
      - internal_net
      - db_net
    depends_on:
      - wikijs-postgres

  wikijs-postgres:
    image: postgres:17.2
    container_name: wikijs-postgresql
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=wikijs-postgresql
      - POSTGRES_DB=${WIKIJS_DB_NAME}
      - POSTGRES_USER=${WIKIJS_DB_USER}
      - POSTGRES_PASSWORD=${WIKIJS_DB_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/wikijs/postgres:/var/lib/postgresql/data
    labels:
      - "kuma.monitoring.group.name=Productivity"
      - "kuma.uptime_kuma.name=Wiki.js Database"
      - "kuma.uptime_kuma.tcp.host=wikijs-postgres"
      - "kuma.uptime_kuma.tcp.url=http://wikijs-postgres:5432"
      - "kuma.uptime_kuma.tcp.port=5432"
      - "kuma.uptime_kuma.interval=120"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/postgresql-icon.png"
    ports:
      - "5435:5432"
    networks:
      - db_net

networks:
  internal_net:
    external: true
  db_net:
    external: true