# ============================================================================
# services/security/vaultwarden/docker-compose.yml
# ============================================================================
version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:1.32.5
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=vaultwarden
      - WEBSOCKET_ENABLED=true
      - DOMAIN=https://vault.azuleluna.xyz
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SMTP_HOST=${AUTHENTIK_EMAIL_HOST}
      - SMTP_FROM=${AUTHENTIK_EMAIL_FROM}
      - SMTP_PORT=${AUTHENTIK_EMAIL_PORT}
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${AUTHENTIK_EMAIL_USERNAME}
      - SMTP_PASSWORD=${AUTHENTIK_EMAIL_PASSWORD}
    volumes:
      - ${VAULTWARDEN_PATH}/vaultwarden:/data
    ports:
      - "4743:80"
    labels:
      - "kuma.vaultwarden.name=Vaultwarden"
      - "kuma.vaultwarden.url=http://vaultwarden:80"
      - "kuma.vaultwarden.method=GET"
      - "kuma.vaultwarden.interval=60"
      - "kuma.vaultwarden.keyword=Vaultwarden"
    networks:
      - internal_net

networks:
  internal_net:
    external: true
