version: '3.8'
services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=vaultwarden
    - WEBSOCKET_ENABLED=true
    - DOMAIN=https://vault.azuleluna.xyz
    - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    - SMTP_HOST=${AUTHENTIK_EMAIL_HOST}
    - SMTP_FROM=${AUTHENTIK_EMAIL_FROM}
    - SMTP_PORT=${AUTHENTIK_EMAIL_PORT}
    - SMTP_SECURITY=starttls
    - SMTP_USERNAME=${AUTHENTIK_EMAIL_USERNAME}
    - SMTP_PASSWORD=${AUTHENTIK_EMAIL_PASSWORD}
    volumes:
    - ${VAULTWARDEN_PATH}/vaultwarden:/data
    ports:
    - 4743:80
    labels:
    - kuma.vaultwarden.type=http
    - kuma.vaultwarden.url=http://vaultwarden:80/alive
    - kuma.vaultwarden.name=Vaultwarden
    - kuma.vaultwarden.interval=60
    - kuma.vaultwarden.keyword=alive
    - kuma.vaultwarden.tags=security,passwords
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/vaultwarden-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:4743]
    networks:
    - internal_net
networks:
  internal_net:
    external: true
