# ============================================================================
# services/media/romm/docker-compose.yml
# ============================================================================
version: '3.8'

services:
  romm:
    image: rommapp/romm:3.5.1
    container_name: romm
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=romm
      - DB_HOST=romm-mariadb
      - DB_NAME=${ROMM_DB_NAME}
      - DB_USER=${ROMM_DB_USER}
      - DB_PASSWD=${ROMM_DB_PASSWORD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
    labels:
      - "kuma.romm.name=ROMM"
      - "kuma.romm.url=http://romm:8085"
      - "kuma.romm.method=GET"
      - "kuma.romm.interval=60"
      - "kuma.romm.keyword=ROMM"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/romm-icon.png"
    volumes:
      - ${ROMM_PATH}/romm/resources:/romm/resources
      - ${ROMM_PATH}/romm/config:/romm/config
      - /mnt/user/roms:/romm/library
    ports:
      - "8085:8080"
    networks:
      - internal_net
      - db_net
    depends_on:
      - romm-mariadb

  romm-mariadb:
    image: mariadb:11.6.2
    container_name: romm-MariaDB-Official
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=romm-MariaDB-Official
      - MYSQL_ROOT_PASSWORD=${ROMM_DB_PASSWORD}
      - MYSQL_DATABASE=${ROMM_DB_NAME}
      - MYSQL_USER=${ROMM_DB_USER}
      - MYSQL_PASSWORD=${ROMM_DB_PASSWORD}
    labels:
      - "kuma.rommdb.name=ROMM Database"
      - "kuma.rommdb.tcp.host=romm-mariadb"
      - "kuma.rommdb.tcp.url=http://romm-mariadb:3306"
      - "kuma.rommdb.tcp.port=3306"
      - "kuma.rommdb.interval=120"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/mariadb-icon.png"
    volumes:
      - ${ROMM_PATH}/romm/mariadb:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - db_net

networks:
  internal_net:
    external: true
  db_net:
    external: true