# ============================================================================
# services/networking/pihole/docker-compose.yml
# ============================================================================
version: '3.8'

services:
  pihole:
    image: pihole/pihole:2025.01.0
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - HOST_OS=Unraid
      - HOST_HOSTNAME=JP-Dell
      - HOST_CONTAINERNAME=pihole
      - WEBPASSWORD=${PIHOLE_ADMIN_PASSWORD}
      - PIHOLE_DNS_1=${PIHOLE_DNS1}
      - PIHOLE_DNS_2=${PIHOLE_DNS2}
      - DNSMASQ_LISTENING=all
      - WEB_PORT=8080
    volumes:
      - ${APPDATA_PATH}/pihole/config:/etc/pihole
      - ${APPDATA_PATH}/pihole/dnsmasq.d:/etc/dnsmasq.d
    network_mode: br0
    cap_add:
      - NET_ADMIN