# services/networking/nginx-proxy-manager/docker-compose.yml
# Central reverse proxy for all services - MIGRATED TO NPMplus

version: '3.8'

services:
  nginx-proxy-manager:
    image: zoeyvid/npmplus:2024-12-14-r1
    container_name: NPMplus-Official   
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - HOST_OS=${HOST_OS:-Unraid}
      - HOST_HOSTNAME=${HOST_HOSTNAME:-JP-Dell}
      - HOST_CONTAINERNAME=NPMplus-Official
      - DB_SQLITE_FILE=/data/database.sqlite
      - SUPPRESS_NO_CONFIG_WARNING=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=1
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_FIX_ATTRS_HIDDEN=1
      - S6_KILL_FINISH_MAXTIME=10000
      - S6_VERBOSITY=1
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
      # NPMplus specific environment variables
      - ACME_EMAIL=${ACME_EMAIL}
      - SKIP_IP_RANGES=${SKIP_IP_RANGES:-true}
      - MODSEC=${MODSEC:-false}
      - CROWDSEC=${CROWDSEC:-false}
      - LOGROTATE=${LOGROTATE:-false}
      - GOACCESS=${GOACCESS:-false}
    volumes:
      - ${APPDATA_PATH}/Nginx-Proxy-Manager-Official/data:/data  # SAME: Keep existing data path
      - ${APPDATA_PATH}/Nginx-Proxy-Manager-Official/letsencrypt:/etc/letsencrypt  # SAME: Keep existing SSL path
      - /tmp/Nginx-Proxy-Manager-Official/var/log:/var/log  # SAME: Keep existing log path
    ports:
      - "8090:80"     # HTTP - SAME
      - "8443:443"    # HTTPS - SAME  
      - "8091:81"     # Admin Interface (now HTTPS) - SAME port, but interface is now HTTPS
      - "3003:3000"   # Management API - SAME
    networks:
      # NPM needs access to ALL networks to proxy services
      - public_net
      - internal_net
      - db_net
      - monitoring_net
      - iot_net
      - teslamate_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f -k https://localhost:81/api/health || curl -f http://localhost:81/api/health || exit 1"]  # CHANGED: Updated for HTTPS admin interface
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  public_net:
    external: true
  internal_net:
    external: true
  db_net:
    external: true
  monitoring_net:
    external: true
  iot_net:
    external: true
  teslamate_net:
    external: true