version: '3.8'
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.43.0
    container_name: FileBrowser
    restart: unless-stopped
    privileged: true
    environment:
    - TZ=America/New_York
    - PUID=${PUID}
    - PGID=${PGID}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=FileBrowser
    volumes:
    - /mnt/user/:/srv:rw
    - ${APPDATA_PATH}/filebrowser/:/db/:rw
    ports:
    - 8080:80
    networks:
    - internal_net
    labels:
    - kuma.filebrowser.type=http
    - kuma.filebrowser.url=http://FileBrowser:80
    - kuma.filebrowser.name=File Browser
    - kuma.filebrowser.interval=60
    - kuma.filebrowser.keyword=File Browser
    - kuma.filebrowser.tags=utilities,files
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/filebrowser-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:8080]
    healthcheck:
      test:
      - CMD-SHELL
      - /healthcheck.sh
      interval: 5s
      timeout: 3s
      start_period: 2s
networks:
  internal_net:
    external: true
